runtime: go
vm: true
api_version: go1

handlers:
- url: /
  script: _go_app
- url: /static/.*
  script: _go_app
- url: /checkdomain/.*
  script: _go_app
- url: /status/.*
  script: _go_app
- url: /submit/.*
  script: _go_app
- url: /pending
  script: _go_app
- url: /update
  script: _go_app
- url: /robots.txt
  script: _go_app
- url: /favicon.ico
  script: _go_app